version: "3"

services:
  app:
    container_name: keychain-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    env_file: .env
    depends_on:
      - database
    networks:
      - backend

  web:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - "8001:80"
    networks:
      - backend

  database:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - backend

networks:
  backend:

volumes:
  mysql:
